### ISSUE TITLE
ImportError: cannot import name 'add_dependencies' from 'pcb2blender_importer.blender_addon_utils' (unknown location

### ISSUE THREAD

**Issue by CWE-119** [30350n/pcb2blender#43]
```
bpy.data.window_managers["WinMan"].addon_search = ""
bpy.context.space_data.system_folders_active = 3
Modules Installed (pcb2blender_importer) from 'F:\\blenderPlugins\\pcb2blender_importer_2-8.zip' into 'C:\\Users\\User\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'
Traceback (most recent call last):
  File "G:\Blender\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "G:\Blender\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\pcb2blender_importer\__init__.py", line 16, in <module>
    from .blender_addon_utils import add_dependencies, register_modules_factory
ImportError: cannot import name 'add_dependencies' from 'pcb2blender_importer.blender_addon_utils' (unknown location)


```

**Comment by 30350n** [comment]
That is weird. Can you confirm `C:\\Users\\User\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\pcb2blender_importer\\blender_addon_utils\\__init__.py` exists/make a screenshot of it's contents? (Just open it in any text editor).

**Comment by CWE-119** [comment]
the addons folder is empty, there is no folder no nth

**Comment by CWE-119** [comment]
![image](https://github.com/30350n/pcb2blender/assets/86527233/0b5cf15d-69f5-49f8-bb8f-56546c3e55bb)
![image](https://github.com/30350n/pcb2blender/assets/86527233/86bbd642-d2a9-4f39-b243-43836994d487)

**Comment by CWE-119** [comment]
i fixed it

**Comment by 30350n** [comment]
Oh nice! How?

**Comment by CWE-119** [comment]
idk why the addons file were empty 
i checked the addons file from the source code , there were files 
so i redownloaded and reinstalled , done

**Comment by 30350n** [comment]
Hm okay, odd. Maybe they got flagged by your antivirus software or something. Glad it's resolved now.
